# Generated by Django 3.2.15 on 2022-08-09 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itemdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=255)),
                ('Category', models.CharField(choices=[('RICE', 'Rice'), ('OIL', 'Oil'), ('MILK', 'Milk')], max_length=30)),
                ('Variants', models.CharField(max_length=30)),
                ('Price', models.IntegerField()),
                ('Rating', models.IntegerField()),
                ('reviews', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=50)),
                ('Username', models.CharField(max_length=60)),
                ('Password', models.CharField(max_length=50)),
                ('MobileNumber', models.IntegerField()),
            ],
            options={
                'db_table': 'user_data',
            },
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('ItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Item', to='Groceryapp.itemdetails')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='Groceryapp.usermodel')),
            ],
        ),
    ]
